import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // is not restarted.
        primarySwatch: Colors.blue,

        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('ListView'),
      ),
      body: ListView(
        // shrinkWrap: true,
        scrollDirection: Axis.horizontal,
        itemExtent: 200,
        padding: EdgeInsets.all(8),
        children: <Widget>[
          // Text(
          //   'You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:',
          // ),
          // Text(
          //   'You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:',
          // ),
          // Text(
          //   'You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:',
          // ),
          // Text(
          //   'You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:',
          // ),
          // Text(
          //   'You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:',
          // ),
          // Text(
          //   'You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:',
          // ),
          // Text(
          //   'You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:',
          // ),
          // Text(
          //   'You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:You have pushed the button this many times:',
          // ),
          ListTile(
            leading: Icon(Icons.person),
            title: Text("Account"),
            trailing: Icon(Icons.arrow_right),
          ),
          ListTile(
            leading: Icon(Icons.person),
            title: Text("Account"),
            trailing: Icon(Icons.arrow_right),
          ),
          ListTile(
            leading: Icon(Icons.person),
            title: Text("Account"),
            trailing: Icon(Icons.arrow_right),
          ),
          ListTile(
            leading: Icon(Icons.person),
            title: Text("Account"),
            trailing: Icon(Icons.arrow_right),
          )
        ],
      ),
    );
  }
}
